// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherArchive.Data;

#nullable disable

namespace WeatherArchive.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherArchive.Models.Weather", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("AirHumidity")
                        .HasColumnType("float");

                    b.Property<double>("AtmPressure")
                        .HasColumnType("float");

                    b.Property<double?>("BottomCloudy")
                        .HasColumnType("float");

                    b.Property<double?>("Cloudy")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DewPoint")
                        .HasColumnType("float");

                    b.Property<string>("DirWind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorVisibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SpeedWind")
                        .HasColumnType("float");

                    b.Property<double>("Temp")
                        .HasColumnType("float");

                    b.Property<string>("WeatherCond")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Date");

                    b.ToTable("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
